### ISSUE TITLE
Vape not compatible with trapify

### ISSUE THREAD

**Issue by CrazyPython** [Miserlou/Vape#1]
Installing trapify and then vape gets you this error:

    pkg_resources.DistributionNotFound: The 'xerox==0.3.1' distribution was not found and is required by emo

There exist conflicting version requirements in the requirements.txt.

**Comment by CrazyPython** [comment]
It appears the changes have been made and merged on [emo/#4](https://github.com/Miserlou/Emo/pull/4), but have not been updated on pip. (fresh install)

**Comment by Miserlou** [comment]
Amazing find.

**Comment by Miserlou** [comment]
Emo version updated. Thanks for the report!

**Comment by CrazyPython** [comment]
Using `>=` will probably reduce incompatibilities with other packages.
